name: Build markdown from YAML data

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/cybersight-ai/python-markdown-generator  
        pip install -r requirements.txt; 
    - name: Create views directory
      run: |
        mkdir -p ./views
    - name: Generate publications view
      run: |
        python ./src/generate_publications_view.py
        ls -l
        ls ./views
    - name: Commit views
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add views/publications.md
        git commit -m "Generation of publication views"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
